export default {
  ui: {
    skip: 'Skip to content',
    menu: 'Menu',
    close: 'Close',
    nav: { about: 'About', services: 'Services', concepts: 'Concepts', packages: 'Packages', process: 'Process', contacts: 'Contact' },
    cta: 'Send a request',
    ctaSecondary: 'Explore services',
    more: 'Learn more',
    home: 'Home',
    services: 'Services',
    language: 'Language',
    call: 'Call',
    whatsapp: 'Message on WhatsApp',
    contactPerson: 'manager',
    footerTagline: 'Event agency based in Astana. We produce events of any format and scale across Kazakhstan.',
    rights: 'All rights reserved.',
    privacy: 'Privacy policy',
    related: 'Other services',
    included: "What's included",
    formats: 'Formats and ideas',
    why: 'Why Sparks',
  },

  form: {
    title: "Let's talk about your event",
    text: "Leave a request and we'll call you back within one business day, ask a few questions and suggest a concept that fits your budget, format and guest count.",
    name: 'Name',
    phone: 'Phone',
    type: 'Event format',
    typePlaceholder: 'Choose a format',
    types: {
      corporate: 'Corporate event',
      newyear: 'New Year corporate party',
      forum: 'Forum / conference',
      wedding: 'Wedding',
      teambuilding: 'Team building',
      private: 'Private event',
      other: 'Other',
    },
    date: 'Date',
    guests: 'Guests',
    message: 'Comments',
    messagePlaceholder: 'City, venue, programme wishes',
    consent: 'I agree to the processing of my personal data under the',
    consentLink: 'privacy policy',
    submit: 'Send request',
    sending: 'Sending…',
    success: "Thank you! We've received your request and will be in touch shortly.",
    error: "We couldn't send your request. Please call us or message us on WhatsApp.",
    invalid: 'Please check the form: name, phone and consent are required.',
    required: 'required',
  },

  home: {
    title: 'Sparks — Event Agency in Astana, Kazakhstan | Corporate Events',
    description: 'Sparks is a full-service event agency in Astana, Kazakhstan: corporate parties, New Year events, business forums, weddings and team building. Concept, artists, production and on-site coordination.',
    eyebrow: 'Turnkey events · Astana',
    h1: 'We create events people remember',
    lead: 'Corporate parties, forums, weddings and gala nights of any scale, fully managed from the first brief to the final report.',
    about: {
      label: 'About',
      title: 'Who we are',
      p: [
        '<strong>Sparks</strong> is an event agency. We produce events of any format and scale, from intimate corporate dinners to grand gala nights and international forums.',
        'Our strength is in the details: a well-crafted programme, professional artists, precise logistics and full support from the brief to the final report.',
        'We take care of everything: concept, artist booking, technical production, décor and on-the-day coordination. The result is an evening your team will talk about all year.',
      ],
      facts: [
        { n: '5,000+', t: 'guests at our largest international forum' },
        { n: '360°', t: 'full cycle: idea, production, coordination' },
        { n: '3', t: 'working languages: Kazakh, Russian, English' },
      ],
    },
    servicesLabel: 'Services',
    servicesTitle: 'What we do',
    conceptsLabel: 'Concepts',
    conceptsTitle: 'A concept made for your night',
    conceptsNote: "We'll tailor the programme to your budget, guest count and format.",
    packagesLabel: 'Packages',
    packagesTitle: 'Turnkey New Year corporate party',
    packagesText: 'Three ready-made packages, from a vibrant evening to a premium programme with a live band. Any service can be added to the package you choose.',
    packagesLink: "See what's included",
    processLabel: 'Process',
    processTitle: 'From brief to result',
    faqLabel: 'FAQ',
    faqTitle: 'Frequently asked questions',
    faq: [
      { q: 'What kinds of events does Sparks organise?', a: 'Corporate and New Year parties, business forums and conferences, weddings, team building, product launches, openings, private celebrations and show programmes of any format and scale.' },
      { q: 'Where do you work?', a: 'We are based in Astana, run events across Kazakhstan and travel to other cities and countries when a project calls for it.' },
      { q: 'How much does an event cost?', a: 'It depends on the format, number of guests and programme. We prepare an exact estimate after a short brief: send a request or give us a call.' },
      { q: 'How far in advance should we book?', a: 'Ideally 3–6 weeks ahead for a corporate party and 2–3 months for a forum or wedding. In the December season the best dates and artists are booked early.' },
      { q: 'Can you build a custom programme?', a: 'Yes. Packages are only a starting point: we design a concept around your budget, guest count and format, and add artists, décor, photo and video.' },
    ],
  },

  process: [
    { t: 'Brief', d: 'We discuss your goals and gather requirements' },
    { t: 'Concept', d: 'We develop the core idea' },
    { t: 'Production', d: 'We build and deliver every element' },
    { t: 'Event', d: 'We run the event on the day' },
  ],

  concepts: [
    { img: 'concept-awards', t: 'New Year Awards', d: 'A corporate awards night with nominations and staff recognition' },
    { img: 'concept-casino', t: 'Casino Night', d: 'Casino show, croupiers and gaming entertainment' },
    { img: 'concept-party', t: '90s / 2000s Party', d: 'The music, dance battles and atmosphere of the era' },
    { img: 'concept-masquerade', t: 'Masquerade Night', d: 'Masks, red carpet, a show programme and décor' },
    { img: 'concept-gala', t: 'Gala Night', d: 'Premium format: live band, saxophone, red carpet and ceremony' },
  ],

  packages: {
    title: 'New Year party packages',
    rowsTitle: 'Programme',
    names: ['Standard', 'Premium', 'Luxury'],
    rows: [
      ['Host + interactive games', 1, 1, 1],
      ['Boys Band — vocal and dance show', 1, 1, 1],
      ['Dance interactive / belly dance', 1, 1, 1],
      ['Hostesses to welcome and guide guests', '1', '2', '3'],
      ['Father Frost and Snow Maiden', 1, 1, 1],
      ['GoldStep Colombian dance show', 1, 1, 1],
      ['DJ set for the whole evening', 1, 1, 1],
      ['Photo booth with prints and digital copies', 1, 1, 1],
      ['Stand-up comedian', 0, 1, 1],
      ['Live band', 0, 0, 1],
    ],
    onRequest: 'Price on request',
    priceNote: 'We price every event around your format, venue and guest count.',
    priceCta: 'Get a quote',
    luxuryNote: 'Luxury is for companies that expect a flawless experience: live music, a spectacular show and a true celebration your guests will remember.',
    addonsTitle: 'Extend the programme',
    addonsText: 'Any of these services can be added to the package you choose.',
    addons: [
      { t: 'Photographer' },
      { t: 'Mobile videographer' },
      { t: 'Same Day Edit', d: 'An edited video on the day of the event' },
      { t: 'Photo zone' },
      { t: 'Red carpet', d: 'With stanchions' },
      { t: 'Photo booth' },
      { t: 'Programmed lighting' },
      { t: 'Saxophone' },
      { t: 'Interactive programmes' },
      { t: 'Artists and celebrities', d: 'On request' },
      { t: 'Décor and additional acts', d: 'On request' },
    ],
  },

  services: {
    'corporate-events': {
      name: 'Corporate events',
      short: 'Turnkey corporate events, from intimate evenings to company-wide celebrations.',
      title: 'Corporate Event Planning in Astana | Sparks',
      description: 'Turnkey corporate event planning: concept, host, artists, DJ, décor, photo and video. From intimate dinners to celebrations for hundreds of guests. Sparks Event Agency.',
      h1: 'Corporate event planning',
      lead: 'We design and run turnkey corporate events, from intimate evenings to large-scale celebrations. You set the goal and we handle everything else.',
      img: 'guests',
      includes: [
        "Concept and script built around your company's goals",
        'Venue, catering and supplier selection',
        'Host, artists, show programme and DJ',
        'Sound, lighting, stage and technical production',
        'Décor, photo zones and a welcome area',
        'Photo, video and Same Day Edit',
        'On-the-day coordination and a final report',
      ],
      formats: [
        { t: 'Company anniversary', d: 'Ceremony, awards, show and banquet' },
        { t: 'Summer corporate party', d: 'Off-site format, outdoor activities and an evening programme' },
        { t: 'Corporate awards', d: 'Nominations, ceremony, red carpet' },
        { t: 'Themed party', d: 'Casino, Masquerade, 90s/2000s, Gala Night' },
      ],
      why: [
        'One dedicated manager from brief to report',
        'Trusted artists and suppliers',
        'A programme that fits your budget, with no hidden fees',
      ],
      formType: 'corporate',
    },
    'new-year-corporate': {
      name: 'New Year corporate party',
      short: 'A complete New Year evening: welcome area, show, interactive games, photo zones and live music.',
      title: 'Turnkey New Year Corporate Party in Astana | Sparks',
      description: 'Turnkey New Year corporate party in Astana and across Kazakhstan: host, show programme, Father Frost and Snow Maiden, DJ, photo booth, live band. Standard, Premium and Luxury packages.',
      h1: 'Turnkey New Year corporate party',
      lead: "We'll create a complete New Year evening for your team, from the guest welcome and welcome area to a spectacular show, interactive games and a closing live performance.",
      img: 'dj',
      includes: [
        'Hosts and show: professional hosts, music and dance acts',
        'DJ and music: live music, DJ set and saxophone all evening',
        'Interactive games: contests, games and festive surprises for guests',
        'Photo zones: festive photo zones, a photo booth, prints and digital formats',
      ],
      formats: null,
      why: [
        'Ready-made packages for any scale',
        'Themed concepts: Awards, Casino, Masquerade, Gala',
        'Flexible add-ons to match your budget',
      ],
      formType: 'newyear',
      showPackages: true,
    },
    'business-forums': {
      name: 'Business forums and conferences',
      short: 'Business events across Kazakhstan and international forums for 5,000+ guests.',
      title: 'Business Forum and Conference Organisation in Astana | Sparks',
      description: 'We organise business forums, conferences and international events for 5,000+ guests: concept, production, venue, registration, speakers and coordination.',
      h1: 'Business forum and conference organisation',
      lead: 'We run large-scale business events across Kazakhstan, from concept and production to venue and guest coordination. Our portfolio includes an international forum for 5,000+ attendees with speakers, partners and guests from many countries.',
      img: 'handshake',
      includes: [
        'Concept, script and timing of the business programme',
        'Venue, build, stage, screens and live streaming',
        'Registration, badges, wayfinding and hostesses',
        'Speaker, moderator and partner management',
        'Transfers, accommodation and guest logistics',
        'Simultaneous interpreting and multilingual support',
        'Photo, video, press area and post-event release',
      ],
      formats: [
        { t: 'Forum', d: 'Plenary sessions, panels and an exhibition area' },
        { t: 'Conference', d: 'Business programme and networking' },
        { t: 'Product launch', d: 'A show-style launch for partners and press' },
        { t: 'Dealer meeting', d: 'Programme, awards and an evening reception' },
      ],
      why: [
        'Experience with events for 5,000+ guests',
        'We work in three languages',
        'One production team instead of a dozen suppliers',
      ],
      formType: 'forum',
    },
    weddings: {
      name: 'Weddings',
      short: 'Bespoke concepts, show programmes and atmosphere for life’s special moments.',
      title: 'Wedding Planning in Astana | Sparks Event Agency',
      description: 'Full-service wedding planning: concept, décor, host, artists, live band, photo and video, and on-the-day coordination. Sparks Event Agency.',
      h1: 'Wedding planning',
      lead: 'We create bespoke concepts, show programmes and atmosphere for your most special day. You enjoy the celebration while we take care of every detail.',
      img: 'gala',
      includes: [
        'Concept, styling and décor',
        'Venue and supplier selection',
        'Host, artists, live band and saxophone',
        'Show programme and surprises for guests',
        'Photo, video and Same Day Edit',
        'A coordinator on the wedding day',
      ],
      formats: [
        { t: 'Wedding and toi', d: 'Traditions meet a modern show programme' },
        { t: 'Kyz uzatu', d: "A warm evening for the bride's family" },
        { t: 'Destination ceremony', d: 'A ceremony outdoors or at a special venue' },
        { t: 'Intimate wedding', d: 'A small circle, atmosphere and attention to detail' },
      ],
      why: [
        'A bespoke concept, never a template',
        'Careful timing with no gaps or mix-ups',
        'A coordinator who handles everything for you',
      ],
      formType: 'wedding',
    },
    'team-building': {
      name: 'Team building',
      short: 'Interactive programmes and team activities that turn an ordinary day into an event.',
      title: 'Corporate Team Building in Astana | Sparks',
      description: 'Team building for companies: quests, sports and creative programmes, off-site formats. We bring your people together and turn an ordinary day into an event.',
      h1: 'Team building for companies',
      lead: 'Interactive programmes and team activities that bring colleagues together and turn an ordinary working day into an event.',
      img: 'party',
      includes: [
        'A programme built around your goals: bonding, onboarding, motivation',
        'Professional hosts and facilitators',
        'Props, venue and equipment',
        'Transfers and catering for off-site formats',
        'Photo, video and a highlights film',
      ],
      formats: [
        { t: 'Quest', d: 'Team challenges around the city or at a venue' },
        { t: 'Sports team building', d: 'Relays, games and competitions' },
        { t: 'Creative format', d: 'Cooking, music or art challenge' },
        { t: 'Off-site format', d: 'An outdoor programme followed by dinner' },
      ],
      why: [
        'A programme tailored to the size and age of your team',
        'Formats for small teams and whole companies alike',
        'Highlights film and photos for internal communications',
      ],
      formType: 'teambuilding',
    },
    'private-events': {
      name: 'Private events and shows',
      short: 'Launches, openings, birthdays, parties, show programmes and custom event projects.',
      title: 'Private Events, Launches and Openings in Astana | Sparks',
      description: 'We organise birthdays, parties, product launches, openings and show programmes. Concept, artists, décor and coordination, fully managed.',
      h1: 'Private events, launches and shows',
      lead: 'Product launches, openings, private celebrations, parties, show programmes and custom event projects. Every idea comes with a well-crafted concept and flawless execution.',
      img: 'masquerade',
      includes: [
        'Event idea and concept',
        'Venue, décor and photo zones',
        'Artists, celebrities and show acts on request',
        'Lighting, sound and special effects',
        'Photo, video and mobile content',
      ],
      formats: [
        { t: 'Birthday and anniversary', d: 'A personal programme and surprises' },
        { t: 'Opening', d: 'Restaurant, boutique, showroom or office' },
        { t: 'Launch', d: 'A product or brand launch' },
        { t: 'Themed party', d: 'Casino, Masquerade, 90s/2000s' },
      ],
      why: [
        'Original ideas and strong production',
        'Artists and celebrities on request',
        'Discretion and attention to detail',
      ],
      formType: 'private',
    },
  },

  alts: {
    'concept-awards': 'Illustration: a trophy under spotlights — New Year Awards',
    'concept-casino': 'Illustration: roulette wheel, playing cards and chips — Casino Night',
    'concept-party': 'Illustration: disco ball and cassette tape — 90s/2000s party',
    'concept-masquerade': 'Illustration: Venetian mask and red carpet — Masquerade Night',
    'concept-gala': 'Illustration: crystal chandelier and champagne coupes — Gala Night',
    logo: 'Sparks Event Agency logo',
    dj: 'DJ performing at a Sparks corporate event',
    handshake: 'A guest receiving an award at a Sparks event',
    guests: 'Guests at a Sparks corporate evening around a cocktail table',
    party: 'Neon-lit dance floor at a 90s and 2000s themed party',
    masquerade: 'Masked guests on the red carpet at Masquerade Night',
    gala: 'Saxophonist performing at a gala night in a chandelier-lit hall',
  },
  privacy: {
    title: 'Privacy Policy | Sparks',
    description: 'How Sparks Event Agency collects, uses and protects the personal data you share on this website.',
    h1: 'Privacy policy',
    updated: 'Last updated: 25 September 2026.',
    sections: [
      ['General', 'This policy explains how Sparks Event Agency ("Sparks", "we") processes the personal data of website visitors in accordance with the Law of the Republic of Kazakhstan "On Personal Data and Its Protection".'],
      ['Data we collect', 'Through the request form we receive your name, phone number, event format and date, number of guests and your comments. The server also automatically logs technical data: IP address, browser type and request time.'],
      ['Why we use it', 'We use your data only to contact you, prepare a proposal and organise your event. We will not send you marketing messages without separate consent.'],
      ['Sharing with third parties', 'We do not sell or share your data with third parties, except suppliers directly involved in your event and where required by law.'],
      ['Storage and protection', 'Data is kept on secure servers for no longer than needed for these purposes, or until you withdraw your consent.'],
      ['Your rights', 'You may request access to, correction or deletion of your data, or withdraw your consent, by contacting us using the details on this website.'],
      ['Cookies', 'This website does not use advertising or analytics cookies. Your chosen language may be stored in your browser for convenience.'],
    ],
  },

  thanks: {
    title: 'Request sent | Sparks',
    description: 'Thank you for contacting Sparks Event Agency.',
    h1: "Thank you! We've received your request",
    text: 'Our manager will contact you within one business day. If it is urgent, call us or message us on WhatsApp.',
    back: 'Back to home',
  },

  notFound: {
    title: 'Page not found | Sparks',
    description: 'This page does not exist on the Sparks Event Agency website.',
    h1: 'Page not found',
    text: 'The link may be outdated or the address mistyped. Start from the home page or choose a service.',
    back: 'Go to home page',
  },
};
